### ISSUE TITLE
new feature "pick and place" causes complie failure

### ISSUE THREAD

**Issue by IcarusWizard** [HITROS/omtb#3]
After adding new features, `catkin_make` throw error:
```
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_install_python.cmake:56 (message):
  catkin_install_python() called with non-existing file
  '/home/icarus/omtb/github/src/omtb_control/nodes/pick_and_place.py'.
Call Stack (most recent call first):
  omtb_control/CMakeLists.txt:71 (catkin_install_python)


-- Configuring incomplete, errors occurred!
See also "/home/icarus/omtb/github/build/CMakeFiles/CMakeOutput.log".
See also "/home/icarus/omtb/github/build/CMakeFiles/CMakeError.log".
```

**Comment by Krada-Jhin** [comment]
same error after install packages

**Comment by hitfuyu** [comment]
> After adding new features, `catkin_make` throw error:
> 
> ```
> -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
> CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_install_python.cmake:56 (message):
>   catkin_install_python() called with non-existing file
>   '/home/icarus/omtb/github/src/omtb_control/nodes/pick_and_place.py'.
> Call Stack (most recent call first):
>   omtb_control/CMakeLists.txt:71 (catkin_install_python)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/icarus/omtb/github/build/CMakeFiles/CMakeOutput.log".
> See also "/home/icarus/omtb/github/build/CMakeFiles/CMakeError.log".
> ```

The bug has been fixed. @IcarusWizard @Krada-Jhin
