### ISSUE TITLE
error in  cartographer 

### ISSUE THREAD

**Issue by Krada-Jhin** [HITROS/omtb#4]
after download cartographer_ros by git . if I choose to git clone the cartographer in the same src in workspace, then it will show:
--------------------------------------------------------------------------------------------------
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:95 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:63 (catkin_workspace)

-- Configuring incomplete, errors occurred!
See also "/home/sparta/catkin_slam/build/CMakeFiles/CMakeOutput.log".
See also "/home/sparta/catkin_slam/build/CMakeFiles/CMakeError.log".
-------------------------------------------------------------------------
**************************************************************
to avoid this bug ,I choose apt-get cartographer. However , there is another error below,
and " sudo apt-get install ros-kinetic-abseil-cpp " did not work . A blog in google think I get a old meta and a new meta ,but it seems they both new...
------------------------------------------------------------------------
*********************************************************************
CMake Error at cartographer_ros/cartographer_ros/CMakeLists.txt:57 (find_package):

By not providing "FindAbseil.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Abseil", but
  CMake did not find one.

  Could not find a package configuration file provided by "Abseil" with any
  of the following names:

    AbseilConfig.cmake
    abseil-config.cmake

  Add the installation prefix of "Abseil" to CMAKE_PREFIX_PATH or set
  "Abseil_DIR" to a directory containing one of the above files.  If "Abseil"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by hitfuyu** [comment]
Please follow [https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html#building-installation](url) to install cartographer.
Besides, before compiling， the site in the file “cartographer_ros.rosinstall” 
`'https://ceres-solver.googlesource.com/ceres-solver.git'`
should be replaced by
`'https://github.com/ceres-solver/ceres-solver.git'`

**Comment by JunYiShih** [comment]
http://www.ceres-solver.org/  
Just download and build here. 
It's an open source library for modeling and solving large, complicated optimization problems.
It's a product made by Google, so we have to cross the _wall_ in mainland.
