### ISSUE TITLE
测试更新声明

### ISSUE THREAD

**Issue by Krada-Jhin** [HITROS/omtb#6]
完成了gmapping相关test,具体内容更新在了我的fork:Kardar-Jhin/omtb (branch:sparta) 
更新了三个测试房间,新增omtb_test.用于测试.
由于pull request显示There isn’t anything to compare.,可能是文件差距过大,在尝试后并未成功推送.

**Comment by hitfuyu** [comment]
In this case, please save your work, update your local branch, run git-checkout, and then make any modification.
